# Enable or Disable Join Protection (true/false)
joinEnableProtection: true

# Join Protection Time in seconds
joinTimeProtection: 20

# Can Player Move during Join Protection Time (true/false)
joinMovementAllow: true

# You can use color codes to color the messages text: https://www.spigotmc.org/wiki/textcosmetics-colors-and-formats/
# You can use %time% to show remaining seconds
Messages:
  joinCooldownStart: "&2You are protected for &6%time% seconds&2!"
  joinCooldownEnded: "&cYou are no longer protected!"

# Do not change, dev only.
Version: 0.1.0
