# Enable or Disable Join Protection (true/false)
joinProtectionEnable: true

# Join Protection Time in seconds
joinProtectionTime: 20

# Can Player Move during Join Protection Time (true/false)
joinEnableMovement: true

# Enable or Disable Dimension Change Protection (true/false)
dimensionProtectionEnable: true

# Dimension Protection Time in seconds
dimensionProtectionTime: 15

# Can Player Move during Dimension Protection Time (true/false)
dimensionEnableMovement: true

# You can use Colorcodes: "&"
# You can use %time% to show remaining seconds
Messages:
  joinCooldownStart: "&2Protection time started! &6%time% seconds left!"
  joinCooldownEnded: "&4Protection time ended! &cYou are now vulnerable!"
  dimensionCooldownStart: "&2Protection time started! &6%time% seconds left!"
  dimensionCooldownEnded: "&4Protection time ended! &cYou are now vulnerable!"


# Do not change, dev only.
Version: 0.1.1
