name: JoinProtection
version: '${project.version}'
main: me.mcsken.joinprotection.JoinProtection
api-version: 1.19
authors: [ mcsken ]
description: Efficient SpigotMC plugin for preventing damage during player login and dimension change.
website: https://github.com/mcsken
permissions:
  joinProtection.on:
    description: Enables join protection for specified user/group, all by default.
    default: true
  joinProtection.off:
    description: Disables join protection for specified user/group.
    default: false
  dimensionProtection.on:
    description: Enables dimension protection for specified user/group, all by default.
    default: true
  dimensionProtection.off:
    description: Disables dimension protection for specified user/group.
    default: false