name: JoinProtection
version: '${project.version}'
main: me.mcsken.joinprotection.JoinProtection
api-version: 1.19
authors: [ mcsken ]
description: A plugin to protect players while loading when first joined and while changing dimensions.
website: https://github.com/mcsken
permissions:
  joinprotection.ignore:
    description: Ignore the Join Protection
    default: op